#!/usr/bin/env bash

###############################################
# Installing Python
#

package_name="lfortran"
package_version="0.3.0"
SHA=${SHA:-71f64668c259f3ed07bd4aa239dbba6cc1b6b0a84d50bbff160664845d7986f757e4d65fca327e62a2d12ba593742ca83a22f7cb6093aff8715ec916c2ba9416}
SRC_ARCHIVE=${SRC_ARCHIVE:-https://www.python.org/ftp/python/3.7.4/Python-3.7.4.tar.xz}

set -e

source includes/source_includes.sh
 
module purge
require  personal-modules
require  beta-modules
require  gcc-libs/10.2.0
require  compilers/gnu/10.2.0
require  cmake

rm -rf $install_prefix

make_build_env

export PATH="$install_prefix/bin:$PATH"
export LD_LIBRARY_PATH="$install_prefix/lib:$LD_LIBRARY_PATH"

cd "$build_dir"

wget "$SRC_ARCHIVE"

manifest \
    "sha512:$SHA" "Python-${package_version}.tar.xz" 

tar -xf "Python-${package_version}.tar.xz"

cd "Python-${package_version}"
./configure --prefix="$install_prefix" \
            --enable-shared \
            --with-threads \
            --enable-ipv6 \
            --with-ensurepip

make -l "$(nproc)" -j && make install
pip3 install --upgrade pip
pip3 install virtualenv

pip3 install --upgrade pip
pip3 install scikit-build
pip3 install lfortran==${VERSION}

