#!/usr/bin/env bash

set -e


ln -fs /shared/ucl/apps/build_scripts/includes .

for i in ${includes_dir:=$(dirname $0 2>/dev/null)/includes}/{module_maker,require}_inc.sh; do . $i; done

require gcc-libs/4.9.2
require python/3.9.10
require compilers/gnu/4.9.2
require mpi/openmpi/3.1.4/gnu-4.9.2

NAME=${NAME:-dask-mpi}
VERSION=${VERSION:-2021.11.0}
#INSTALL_PREFIX=${INSTALL_PREFIX:-/shared/ucl/apps/$NAME/$VERSION/$COMPILER_TAG}
INSTALL_PREFIX=${INSTALL_PREFIX:-${HOME}/Applications/$NAME/$VERSION}
SRC_ARCHIVE=${SRC_ARCHIVE:-https://github.com/dask/dask-mpi.git}


mkdir -p /dev/shm/$(whoami)/${NAME}

temp_dir=$(mktemp -d -p /dev/shm/$(whoami)/${NAME})

cd $temp_dir

git clone ${SRC_ARCHIVE}

cd ${NAME}

git checkout ${VERSION}
rm -rf ${INSTALL_PREFIX}
pip3 install --target=${INSTALL_PREFIX} dask distributed mpi4py jupyter-server-proxy .

rm -rf $temp_dir
