#!/usr/bin/env bash

set -e


ln -fs /shared/ucl/apps/build_scripts/includes .

for i in ${includes_dir:=$(dirname $0 2>/dev/null)/includes}/{module_maker,require}_inc.sh; do . $i; done

require gcc-libs/4.9.2
require compilers/nvhpc/20.9
NAME=${NAME:-fftw}
VERSION=${VERSION:-3.3.8}
PERFLIBSVER=${PERFLIBSVER:-1.0}
INSTALL_PREFIX=${INSTALL_PREFIX:-${HOME}/Applications/perflibs/$PERFLIBSVER/$NAME/$VERSION/$COMPILER_TAG}
MD5=${MD5:-8aac833c943d8e90d51b697b27d4384d}
COMMON_FLAGS=${COMMON_FLAGS:-"--enable-shared"} 
SRC_ARCHIVE=${SRC_ARCHIVE:-}

export FFLAGS="-Mpreprocess -Mbackslash -O2"
export CFLAGS="-O2"
export CPPFLAGS="-O2"

mkdir -p /dev/shm/$(whoami)/${NAME}

temp_dir=$(mktemp -d -p /dev/shm/$(whoami)/${NAME})

cd $temp_dir

wget $SRC_ARCHIVE
archive=$(basename "${SRC_ARCHIVE}")

md5sum -c <<< "$MD5 $archive"

for i in --enable-float --enable-long-double --enable-quad-precision ""
do
  echo "building $i version"
  tar -xvf $archive

  cd ${NAME}-${VERSION}

  ./configure --prefix=$INSTALL_PREFIX ${COMMON_FLAGS} $i
  make 
  make install

  cd ..
  rm -rf ${NAME}-${VERSION}
  echo "building $i version complete"

done

rm -rf $temp_dir
