#!/usr/bin/env bash

set -e


ln -fs /shared/ucl/apps/build_scripts/includes .

for i in ${includes_dir:=$(dirname $0 2>/dev/null)/includes}/{module_maker,require}_inc.sh; do . $i; done

require gcc-libs/4.9.2
require compilers/nvhpc/20.9

NAME=${NAME:-openblas}
VERSION=${VERSION:-0.3.7}
PERFLIBSVER=${PERFLIBSVER:-1.0}
INSTALL_PREFIX=${INSTALL_PREFIX:-${HOME}/Applications/perflibs/$PERFLIBSVER/$NAME/$VERSION/$COMPILER_TAG}
SHA512=${SHA512:-9c4898301c675471bbce2bb99b6bbe7c90724784fac06504416d4bd5da3cd4488f727b0a118c9a38ea342daac2af9e32597a847004241cc57de693b58b856262}

SRC_ARCHIVE=${SRC_ARCHIVE:-https://github.com/xianyi/OpenBLAS/archive/v${package_version}.tar.gz}


mkdir -p /dev/shm/$(whoami)/${NAME}

temp_dir=$(mktemp -d -p /dev/shm/$(whoami)/${NAME})

cd $temp_dir

wget $SRC_ARCHIVE
archive=$(basename "${SRC_ARCHIVE}")

sha512sum -c <<< "$SHA512 $archive"

owd="$(pwd -P)"
for package_variant in "serial" "native-threads" "openmp"; do

    make_build_env ""

    cd "$build_dir"

    tar -zxvf "$owd/v${package_version}.tar.gz"

    if [[ "$package_variant" == "serial" ]]; then
        use_threads=0
        use_openmp=0
    elif [[ "$package_variant" == "native-threads" ]]; then
        use_threads=1
        use_openmp=0
    elif [[ "$package_variant" == "openmp" ]]; then
        use_threads=1
        use_openmp=1
    fi 

    cd "OpenBLAS-${package_version}"
    make PREFIX=${install_prefix} DYNAMIC_ARCH=1 USE_THREAD="$use_threads" USE_OPENMP="$use_openmp"

    rm -rf ${install_prefix}
    mkdir -p ${install_prefix}

    make PREFIX=${install_prefix} DYNAMIC_ARCH=1 USE_THREAD="$use_threads" USE_OPENMP="$use_openmp" install

    # Fixes for various packages e.g. numpy with broken search routines.
    cd $install_prefix/lib
    ln -s libopenblas.so liblapack.so
    ln -s libopenblas.so libblas.so
    ln -s libopenblas.a liblapack.a
    ln -s libopenblas.a libblas.a

    cd "$owd"
done

rm -rf $temp_dir
