#!/usr/bin/env bash

set -e


ln -fs /shared/ucl/apps/build_scripts/includes .

for i in ${includes_dir:=$(dirname $0 2>/dev/null)/includes}/{module_maker,require}_inc.sh; do . $i; done

require gcc-libs/4.9.2

YEAR=${YEAR:-2023}
RELEASE=${RELEASE:-23.9}
RELEASE_=$(echo $RELEASE | sed 's|\.||g')
NAME=${NAME:-nvhpc}
VERSION=${VERSION:-${YEAR}_${RELEASE_}}
INSTALL_PREFIX=${INSTALL_PREFIX:-${HOME}/Applications/$NAME/$VERSION/$COMPILER_TAG}
SHA256=${SHA256:-ecf343ecad2398e21c8d7f24a580b2932348017dfd8ea38c1ef31b37114b2d4b}

SRC_ARCHIVE=${SRC_ARCHIVE:-https://developer.download.nvidia.com/hpc-sdk/${RELEASE}/${NAME}_${VERSION}_Linux_x86_64_cuda_multi.tar.gz}


mkdir -p /dev/shm/$(whoami)/${NAME}

temp_dir=$(mktemp -d -p /dev/shm/$(whoami)/${NAME})

cd $temp_dir

wget $SRC_ARCHIVE
archive=$(basename "${SRC_ARCHIVE}")

sha256sum -c <<< "$SHA256 $archive"


tar -xvf $archive

export NVHPC_INSTALL_DIR=${INSTALL_PREFIX}
export NVHPC_SILENT=true

echo $NVHPC_INSTALL_DIR

cd ${NAME}_${VERSION}_Linux_x86_64_cuda_multi
./install

rm -rf $temp_dir
