#!/usr/bin/env bash

set -e


ln -fs /shared/ucl/apps/build_scripts/includes .

for i in ${includes_dir:=$(dirname $0 2>/dev/null)/includes}/{module_maker,require}_inc.sh; do . $i; done

require gcc-libs/4.9.2

NAME=${NAME:-nvhpc}
VERSION=${VERSION:-2020_207}
#INSTALL_PREFIX=${INSTALL_PREFIX:-/shared/ucl/apps/$NAME/$VERSION/$COMPILER_TAG}
INSTALL_PREFIX=${INSTALL_PREFIX:-${HOME}/Applications/$NAME/$VERSION/$COMPILER_TAG}
MD5=${MD5:-80b629653121c521317249c7cdb7bb30}

SRC_ARCHIVE=${SRC_ARCHIVE:-https://developer.download.nvidia.com/hpc-sdk/${NAME}_${VERSION}_Linux_x86_64_cuda_multi.tar.gz}


mkdir -p /dev/shm/$(whoami)/${NAME}

temp_dir=$(mktemp -d -p /dev/shm/$(whoami)/${NAME})

cd $temp_dir

wget $SRC_ARCHIVE
archive=$(basename "${SRC_ARCHIVE}")

md5sum -c <<< "$MD5 $archive"


tar -xvf $archive

export NVHPC_INSTALL_DIR=$INSTALL_PREFIX

cd ${NAME}_${VERSION}_Linux_x86_64_cuda_multi
./install
