#!/usr/bin/env bash

###############################################
# Installing f18 from git
#
# by Owain Kenway, 2019
#
set -e

for i in ${includes_dir:=$(dirname $0 2>/dev/null)/includes}/{module_maker,require}_inc.sh; do . $i; done

module purge
require beta-modules
require personal-modules
require gcc-libs/7.3.0
require compilers/gnu/7.3.0
require llvm/8.0.0/gnu-7.3.0
require cmake/3.13.3

NAME=${NAME:-f18}
VERSION=${VERSION:-git}
INSTALL_PREFIX=${INSTALL_PREFIX:-$HOME/Applications/$NAME/$VERSION}

SRC_ARCHIVE=${SRC_ARCHIVE:-https://github.com/flang-compiler/f18.git}


mkdir -p /dev/shm/$(whoami)/${NAME}

temp_dir=$(mktemp -d -p /dev/shm/$(whoami)/${NAME})

cd $temp_dir

git clone $SRC_ARCHIVE
cd ${NAME}
mkdir build
cd build
ccmake -DCMAKE_INSTALL_PREFIX=$INSTALL_PREFIX -DCMAKE_BUILD_TYPE=Release ..
make -j 8
make install

rm -rf $temp_dir
