#!/usr/bin/env bash

# Massive thanks to Jeff Hammond (@jeffhammond) for the example:
# https://github.com/jeffhammond/HPCInfo/blob/master/buildscripts/llvm-git.sh

set -e

ln -fs /shared/ucl/apps/build_scripts/includes .

for i in ${includes_dir:=$(dirname $0 2>/dev/null)/includes}/{module_maker,require}_inc.sh; do . $i; done

module purge
require beta-modules
require personal-modules
require gcc-libs/10.2.0
require compilers/gnu/10.2.0
require cmake/3.21.1
require python/3.9.10
require ninja

NAME=${NAME:-llvm-flang-fir}
VERSION=${VERSION:-testing}
#INSTALL_PREFIX=${INSTALL_PREFIX:-/shared/ucl/apps/$NAME/$VERSION/$COMPILER_TAG}
INSTALL_PREFIX=${INSTALL_PREFIX:-${HOME}/Applications/$NAME/$VERSION}

SRC_ARCHIVE=${SRC_ARCHIVE:-https://github.com/flang-compiler/f18-llvm-project.git}

loc=$(pwd)

mkdir -p /dev/shm/$(whoami)/${NAME}

temp_dir=$(mktemp -d -p /dev/shm/$(whoami)/${NAME})

cd $temp_dir

git clone -b fir-dev --single-branch --recursive $SRC_ARCHIVE
#cd f18-llvm-project
#git checkout fir-dev -b fir-dev || echo exists
#git branch --set-upstream-to=origin/fir-dev fir-dev || echo dunno
#git pull
#git submodule update --init --recursive
#cd ..
tar -cf $loc/flang-fir-${VERSION}.tar f18-llvm-project
