#!/usr/bin/env bash

set -e


ln -fs /shared/ucl/apps/build_scripts/includes .

for i in ${includes_dir:=$(dirname $0 2>/dev/null)/includes}/{module_maker,require}_inc.sh; do . $i; done

require gcc-libs/4.9.2
require python/3.9.10

NAME=${NAME:-jupyterlab}
VERSION=${VERSION:-current}
#INSTALL_PREFIX=${INSTALL_PREFIX:-/shared/ucl/apps/$NAME/$VERSION/$COMPILER_TAG}
INSTALL_PREFIX=${INSTALL_PREFIX:-${HOME}/Applications/$NAME/$VERSION}

rm -rf ${INSTALL_PREFIX}

virtualenv ${INSTALL_PREFIX}
source ${INSTALL_PREFIX}/bin/activate

pip3 install --upgrade pip
pip3 install jupyterlab
pip3 install numpy numba matplotlib
