#!/usr/bin/env bash

###############################################
# Installing f18 from git
#
# by Owain Kenway, 2019
#
set -e

for i in ${includes_dir:=$(dirname $0 2>/dev/null)/includes}/{module_maker,require}_inc.sh; do . $i; done

require gcc-libs/4.9.2
require llvm/8.0.0/gnu-4.9.2
require cmake/3.13.3

NAME=${NAME:-f18}
VERSION=${VERSION:-git}
INSTALL_PREFIX=${INSTALL_PREFIX:-$HOME/Applications/$NAME/$VERSION}

SRC_ARCHIVE=${SRC_ARCHIVE:-https://github.com/flang-compiler/f18.git}


mkdir -p /dev/shm/$(whoami)/${NAME}

temp_dir=$(mktemp -d -p /dev/shm/$(whoami)/${NAME})

cd $temp_dir

git clone $SRC_ARCHIVE
cd ${NAME}
mkdir build
cd build
export CXX=clang++
ccmake -DCMAKE_INSTALL_PREFIX=$INSTALL_PREFIX -DBUILD_WITH_CLANG=/shared/ucl/apps/llvm/8.0.0/gnu-4.9.2 -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS=-stdlib=libc++ ..
make 
make install

rm -rf $temp_dir
