#!/usr/bin/env bash

# MPM as per https://github.com/mathworks-ref-arch/matlab-dockerfile/blob/main/MPM.md

set -e

ln -fs /shared/ucl/apps/build_scripts/includes .

for i in ${includes_dir:=$(dirname $0 2>/dev/null)/includes}/{module_maker,require}_inc.sh; do . $i; done

require gcc-libs/4.9.2

NAME=${NAME:-mpm}
VERSION=${VERSION:-live}
#INSTALL_PREFIX=${INSTALL_PREFIX:-/shared/ucl/apps/$NAME/$VERSION/$COMPILER_TAG}
INSTALL_PREFIX=${INSTALL_PREFIX:-${HOME}/Applications/$NAME/$VERSION}
#SHA256=${SHA256:-11a494cf34dafe3cdd541d52a03dabb5d1658c97a8053dba57bfa3869772fc3b}
SHA256=${SHA256:-61d2f7a41273dc6bc67d22fec00aa7910193f95b679aa574424d8307d88397a6}

SRC_ARCHIVE=${SRC_ARCHIVE:-https://www.mathworks.com/mpm/glnxa64/mpm}


mkdir -p /dev/shm/$(whoami)/${NAME}

temp_dir=$(mktemp -d -p /dev/shm/$(whoami)/${NAME})

# This file is not included in the archive as it contains some matlab IP.
cp script.patch $temp_dir

cd $temp_dir

wget $SRC_ARCHIVE
archive=$(basename "${SRC_ARCHIVE}")

sha256sum -c <<< "$SHA256 $archive"

head -n +20 $archive > script
tail -n +21 $archive > zip

# This file is not included in the archive as it contains some matlab IP.
patch < script.patch

rm $archive

cp script mpm
cat zip >> mpm

rm -rf ${INSTALL_PREFIX}
mkdir -p ${INSTALL_PREFIX}/bin
cp ${archive} ${INSTALL_PREFIX}/bin
chmod +x ${INSTALL_PREFIX}/bin/${archive}

rm -rf $temp_dir
